/**
 * Copyright (c) 2011, salesforce.com, inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 *    Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *    following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
 *    the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *    Neither the name of salesforce.com, inc. nor the names of its contributors may be used to endorse or
 *    promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package com.force.sdk.codegen.selector;

import static com.force.sdk.codegen.ForceJPAClassGeneratorUtils.*;

import java.util.*;

import com.force.sdk.codegen.ForceJPAClassGeneratorUtils;
import com.force.sdk.codegen.template.Template;
import com.force.sdk.jpa.model.*;
import com.sforce.soap.partner.*;

/**
 * A {@link DataSelector} that selects data to generate Java classes which conform to
 * the Force.com JPA implementation.
 * <p>
 * The files generated by this {@code DataSelector} will also use the JPA class hierarchy
 * conveniently defined by the Force.com JPA implementation (see {@link BaseForceObject}, 
 * {@link BaseForceStandardObject} and {@link BaseForceCustomObject}).
 * 
 * @author Tim Kral
 */
public class ForceJPAClassDataSelector implements DataSelector {

    // Allow a static package name (as opposed to a dynamically
    // generated package name)
    private String packageName;
    
    /**
     * Sets the Java package name under which Java JPA classes
     * are to be generated.
     * 
     * @param packageName a non {@code null} {@code String} which conforms
     *                    to Java package naming standards
     * @see ForceJPAClassGeneratorUtils#constructPackageName(GetUserInfoResult)
     * @see com.force.sdk.codegen.writer.ForceJPAFileWriterProvider#setPackageName(String)
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }
    
    @Override
    public void select(GetUserInfoResult userInfo, DescribeSObjectResult dsr, Template template) {
        if (packageName != null) {
            template.injectView("packageName", packageName);
        } else {
            template.injectView("packageName", ForceJPAClassGeneratorUtils.constructPackageName(userInfo));
        }
        template.injectView("userInfo", userInfo);
        template.injectView("objectInfo", dsr);
        
        selectClassFields(dsr, template);
    }
    
    private void selectClassFields(DescribeSObjectResult dsr, Template template) {
        // This is a list so that field order is always maintained.
        // This is important for gold file testing.
        List<Field> fields = new ArrayList<Field>();
        
        if (dsr.isCustom()) {
            // Skip all fields common to Force.com custom objects
            fields = selectFields(dsr, CUSTOM_OBJECT_COMMON_FIELDS);
        } else if (ForceJPAClassGeneratorUtils.hasAllCommonFields(dsr)) {
            // Skip all fields common to Force.com standard objects
            fields = selectFields(dsr, STANDARD_OBJECT_COMMON_FIELDS);
        } else {
            // Skip all fields common to all Force.com objects
            fields = selectFields(dsr, ALL_OBJECT_COMMON_FIELDS);
        }
        
        template.injectView("fields", fields);
    }
    
    private List<Field> selectFields(DescribeSObjectResult dsr, Set<String> fieldsToSkip) {
        List<Field> fields = new ArrayList<Field>();
        Set<String> javaFieldNames = new HashSet<String>();
        
        for (Field field : dsr.getFields()) {
            String fieldNameLower = field.getName().toLowerCase();
            String javaFieldName = renderJavaName(field, true /*firstCharLowerCase*/);
            
            // Skip over fields in the set
            if (!fieldsToSkip.contains(fieldNameLower)) {
                
                // Check to see if we've already used this Java field name
                if (javaFieldNames.contains(javaFieldName)) {
                    // If there is a Java name conflict, we have a custom field or
                    // relationship name that conflicts with a standard field  
                    // or relationship name. We'll assume that the describe result
                    // orders standard fields before custom ones so below we are adjusting
                    // the custom field or relationship names.
                    
                    if (useRelationshipName(field)) {
                        javaFieldName = javaFieldName + "Relationship";
                        field.setRelationshipName(javaFieldName);
                    } else {
                        javaFieldName = javaFieldName + "Custom";
                        field.setName(javaFieldName);
                    }
                }
                
                fields.add(field);
                javaFieldNames.add(javaFieldName);
            }
        }
        
        return fields;
    }
}
